// BookstoreViewModel.idl
import "BookSku.idl";

namespace Bookstore3
{
	runtimeclass BookstoreViewModel
	{
		BookSku BookSku{ get; };
		Windows.Foundation.Collections.IObservableVector<BookSku> BookSkus{ get; };
	}
}